# Generated by Django 6.0.3 on 2026-03-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prev_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=50)),
                ('event_data', models.JSONField()),
            ],
        ),
    ]
