# Generated by Django 6.0.3 on 2026-03-30 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='created_at',
        ),
        migrations.AddField(
            model_name='block',
            name='ccreated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
