# Generated by Django 6.0.3 on 2026-03-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_remove_block_created_at_block_ccreated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='ccreated_at',
            new_name='created_at',
        ),
    ]
