# Generated by Django 6.0.3 on 2026-04-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_rename_ccreated_at_block_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['index']},
        ),
    ]
