# Generated by Django 6.0.3 on 2026-04-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employeeprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('operator', 'Darbuotojas'), ('manager', 'Vadovas'), ('other', 'Kita')], default='operator', max_length=20),
        ),
    ]
