# Generated by Django 6.0.3 on 2026-03-31 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_machine_task_order_task_priority_task_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_tasks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='part_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('cnc', 'CNC'), ('prep', 'Preparation'), ('welding', 'Welding'), ('painting', 'Painting'), ('qc', 'Quality Control')], default='cnc', max_length=20),
        ),
    ]
