# Generated by Django 6.0.3 on 2026-04-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_machine_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Zemas'), ('medium', 'Vidutinis'), ('high', 'Aukstas'), ('critical', 'Kritinis')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Laukia'), ('in_progress', 'Vykdoma'), ('completed', 'Uzbaigta')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('processing', 'Apdorojimas'), ('preparation', 'Paruosimas'), ('execution', 'Vykdymas'), ('finishing', 'Uzbaigimas'), ('control', 'Kontrole'), ('administration', 'Administravimas'), ('other', 'Kita')], default='processing', max_length=20),
        ),
    ]
